### ISSUE TITLE
model checkpoints at best state

### ISSUE THREAD

**Issue by tmachnitzki** [fiburg/bdp_cnn#14]
save model when val_loss is least or RMSE is least. 
This could even be inside one epoch

**Comment by fiburg** [comment]
@tmachnitzki Wollen wir die bisher offenen issues schließen, für eine bessere Übersicht? Ich denke durch das neue Vorgehen ist das notwendig. Ich würde sagen wir behalten das Projekt "Lorenz" und nutzen für die Issues "lstm" und "cnn" labels

**Comment by fiburg** [comment]
closed due to new project
