### ISSUE TITLE
Verständnis Fehler mit LSTMS!

### ISSUE THREAD

**Issue by tmachnitzki** [fiburg/bdp_cnn#18]
Ich glaube wir hatten bisher einen gigantischen Verständnisfehler bezüglich LSTM (zumindest ich).
LSTMs benutzen ein array mit Zeitschritten, um aufgrund all dieser Zeitschritte einen Einzelnen Zeitschritt vorher zu sagen. Hat unser X also die Dimension (10,100,40), dann bedeutet das, dass unser y nur (10,40) groß sein kann. Es wird also 10 mal versucht aufgrund von 100 Zeitschritten NUR den 101ten Zeitschritt vorher zu sagen. Demnach MÜSSEN wir eine batch-size von größer als 1 verwenden, da sonst nur eine einzige Vorhersage aufgrund des ganzen Datensatzes versucht wird. Weiterhin kann das LSTM immer nur aufgrund der gelernten Größe vorhersagen. Hat es also gelernt aufgrund von 100 Zeitschritten den 101ten Zeitschritt vorher zu sagen, so braucht es IMMER 100 Zeitschritte um eine neue Vorhersage zu machen.
Damit hat es sich für uns wahrscheinlich erledigt LSTMs zu benutzen, da wir ja sonst immer nur mit einer Zeitschrittgröße trainieren könnten, die wir dem Modell auch immer vorlauf geben. Es würde mit unserem 100-schritt beispiel hier also niemals möglich sein eine Vorhersage nur aufgrund von 50 Werten zu erstellen. Machen wir die Trainingsschrittweite jedoch zu klein (z.b. 2), dann würden wir ja so ziemlich den ganzen Vorteil des LSTM gegenüber dem CNN verlieren, müssten uns allerdings immernoch mit all den Problemen rumschlagen. 
(All dies hab ich durch trial and error rausgefunden (und der Keras Dokumentation) und nicht aus irgendwelchen Papern, dass heißt evtl. liege ich auch komplett daneben. Angesichts der Zeit die die ich daran jetzt eigentlich rumgespielt habe glaube ich das eher nicht.)

**Comment by tobifinn** [comment]
Es gibt das Argument ˋreturn_sequencesˋ in ˋkeras.layers.LSTMˋ, damit bekommt man eine Sequenz, d.h. batch_size, time_length, neurons/features als Dimensionen

**Comment by fiburg** [comment]
Tobi hat festgestellt, dass LSTMs weiter genutzt werden können. Wir werden jetzt versuchen basierend auf dem einfachen Lorenzmodell einen Vergleich LSTMs (Tobi) mit CNNs (ich) zu erstellen und dann schauen, wie es weiter geht.

**Comment by tobifinn** [comment]
[Keras issue](https://github.com/keras-team/keras/issues/4870)

Ist das nicht ein ähnliches Problem, wie du auch hast @tmachnitzki ?

**Comment by tmachnitzki** [comment]
Joa, so ähnlich.
Ich habe allerdings gestern schon eine Lösung gefunden mit der ich momentan rumspiele.
Und zwar speicher ich die Gewichte eines Modells welches ich mit einer bestimmten Batch-size trainiere und erstelle dann ein neues Modell mit gleichen Layern aber nur einer batch-size von 1 für die Prediction.

Wenn dich das interessiert schau mal in dem LSTM_testing_tobi branch nach der datei test_generator.py.
Das einzige Problem was ich dort derzeit noch habe ist, dass das Modell nur in 1 von ca. 4 Fällen überhaupt ein Anderes Ergebnis liefert als "-0". Aber wenn es Ergebnisse liefert, dann sind diese meißt auch echt gut. 

Vielen Dank übrigens für deine Mühe @tobifinn  👍
