### ISSUE TITLE
Model Data

### ISSUE THREAD

**Issue by tmachnitzki** [fiburg/bdp_cnn#20]
I just had a first look at the CMIP5 Data and as fas as I can see, these are just available on a monthly scale. Making predictions on such a scale doesn't make any sense in my eyes. I think this is what Stefan was refering to at launch but we didn't understand...

Just for my own interest I had a look now at the DWD data available via ftp and there we could get hourly data of some measurements like temperature pressure rain etc. 
Maybe we should rather try these...

**Comment by fiburg** [comment]
closed due to new project: we use the CMIP5 Data, we are only interested in a trend of the prediction
