### ISSUE TITLE
Consistent output

### ISSUE THREAD

**Issue by t-schanz** [fiburg/bdp_cnn#27]
Have ONE folder for each molder run. In this folder then there will be included the following things:

- Saved Model
- Trained Model Weights
- NC-file with the testing dataset and the predictions
- Scatterplot to have a first overview of the Model run.

The name of the folder should include the date of the initialization of the model run.

This consistent model output would make it very easy to even allow for simple evaluation of all model runs with a single script looping over the folders.

**Comment by tmachnitzki** [comment]
The methods to produce all the files for the folder are already there, they just need to be adjusted, so that everything is saved into one folder
